### ISSUE TITLE
Error "There was an error while parsing the package." while installing MOD.

### ISSUE THREAD

**Issue by askadityapandey** [Team-xManager/xManager#433] opened 2023-12-15 14:18 UTC
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Vivo T1X
- Android Version:  13
- xManager Version:  v 5.2
```

### 📝 Description

1. Open the App.
2. Now, click and download the latest "Stock Patched" Spotify
3. This will throw an error,  "There was an error while parsing the package."

### 📸 Screenshots

![x manager](https://github.com/Team-xManager/xManager/assets/144938685/b821805a-70b7-4817-beba-9605d41407f6)

**Comment by aaditya241106** [comment] 2023-12-15 15:16
Same problem here

**Comment by ciganzelezo** [comment] 2023-12-15 17:01
Same problem here, the manager downloads something else, a much smaller .apk that isn't working, when you click download, go to mirror link, to download the apk from mediafire until it's fixed

**Comment by askadityapandey** [comment] 2023-12-15 18:04
> Same problem here, the manager downloads something else, a much smaller .apk that isn't working, when you click download, go to mirror link, to download the apk from mediafire until it's fixed

Ahh, Yes but the Mediafire link isn't working too now

**Comment by ciganzelezo** [comment] 2023-12-15 18:07
> Ahh, Yes but the Mediafire link isn't working too now

still works for me, at least on the amoled version

**Comment by DarkCrypt** [comment] 2023-12-15 18:27
Duplicate of #432, #423, #353, etc.

You can try what I mentioned in this [comment](https://github.com/Team-xManager/xManager/issues/432#issuecomment-1858306156).

**Comment by xC3FFF0E** [comment] 2023-12-16 08:58
All links should be up by now. Closing.

If the persists, visit one of our support teams for further assistance. Thanks!

**Closed by xC3FFF0E** 2023-12-16 08:58 UTC
