### ISSUE TITLE
Error with the apk

### ISSUE THREAD

**Issue by QuendoDev** [Team-xManager/xManager#422] opened 2023-11-30 09:23 UTC
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Huawei P20
- Android Version:  Android 11
- ROM Version:  stock
- xManager Version:  5.1
```

### 📝 Description

1. When downloading any file (amoled, patched...) it doesnt install (0.07MB???).

**Comment by DarkCrypt** [comment] 2023-11-30 09:30
Duplicate of #353. Incomplete file download.

Always use the MIRROR LINK.

**Comment by QuendoDev** [comment] 2023-11-30 09:32
@DarkCrypt the download is very fast, I cant click on mirror link, could you send the mirror link to me?

**Closed** 2023-11-30 09:39 UTC

**Comment by DarkCrypt** [comment] 2023-11-30 10:00
> could you send the mirror link to me?

Yes.
