### ISSUE TITLE
Parse error, can't install downloaded spotify.

### ISSUE THREAD

**Issue by Echolazy** [Team-xManager/xManager#421] opened 2023-11-30 08:34 UTC
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Infinix hot 11 play
- Android Version:  11
- ROM Version:  global
- xManager Version:  5.1
```

### 📝 Description

1. Parse error when installing Spotify.
2. The xmanager downloaded Spotify in less than 1 MB, so it's a parse error.
3.
...

**Comment by DarkCrypt** [comment] 2023-11-30 09:02
Duplicate of #353. Incomplete file download.

Always use the MIRROR LINK.

**Closed** 2023-11-30 22:29 UTC
