### ISSUE TITLE
Can't parse the file

### ISSUE THREAD

**Issue by MatthiasKiri0303** [Team-xManager/xManager#416] opened 2023-11-29 22:57 UTC
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Samsung M30s
- Android Version:  Android 11
- ROM Version:  stock
- xManager Version:  5.1
```

### 📝 Description

1. Download the apk from the xmanager
2.  Try to install the apk 
3. I get the error can't parse, but only with these patched files, every other apk i am able to install

**Comment by ritose** [comment] 2023-11-30 00:14
Download it from the mirror link that appears when you start the download it worked for me

**Comment by DarkCrypt** [comment] 2023-11-30 08:49
Duplicate of #353. Incomplete file download.

> Download it from the mirror link that appears when you start the download it worked for me

Always use the MIRROR LINK.

**Closed** 2023-11-30 22:24 UTC
