### ISSUE TITLE
Every downloads are 0.07mb files

### ISSUE THREAD

**Issue by lloydinho225** [Team-xManager/xManager#417] opened 2023-11-29 23:11 UTC
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:Samsung Galaxy a21s
- Android Version:Android 12
- ROM Version:stock 
- xManager Version:5.1
```

### 📝 Description

1. just download any mods
the file is about 75kb and ofc doesnt work
tried to download a mod from an other device, had the same issue
edit: mirror links work just fine but the files youvdownload in xmanager itself are bugged

### 📸 Screenshots

![Screenshot_20231130-001832_xManager](https://github.com/Team-xManager/xManager/assets/152449946/84974ff7-e210-4846-b96e-6d7c7e88929c)

**Comment by Meksis** [comment] 2023-11-30 01:17
Actual for me too. Waiting for news!

**Comment by g0blin-tooth** [comment] 2023-11-30 01:38
I thought I was the only one having this problem. It's been like this all day, and I haven't had any problems with xManager before. I hope it gets fixed soon.

**Comment by Iq92** [comment] 2023-11-30 06:09
Yup, mine too

**Comment by DarkCrypt** [comment] 2023-11-30 08:53
Duplicate of #353. Incomplete file download.

> mirror links work just fine

Always use the MIRROR LINK. (See above screenshot)

**Comment by DarkCrypt** [comment] 2023-11-30 17:33
> I've tried these links, but download keeps so many time and, at all, problem will still unresolved anyway.

Disable the ads in Xmanager's in app Settings and try to download the patch, maybe it'll work then.

**Closed** 2023-11-30 22:24 UTC

**Comment by Meksis** [comment] 2023-11-30 22:54
Still don't work. Idk what to do
