### ISSUE TITLE
Corrupted download

### ISSUE THREAD

**Issue by Penguin766** [Team-xManager/xManager#454] opened 2024-02-08 21:19 UTC
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Pixel 7 Pro
- Android Version: Android 14 QPR1 
- ROM Version: Stock  
- xManager Version: 5.2
```

### 📝 Description

1. Trying to open xManager and try to download either the stock, or AMOLED patched mod
2. The download is 0.06MB
3. It verifies the download and signature, and then shows an 'error when parsing package' when trying to install the apk
...

### 📸 Screenshots

![Screenshot_20240208-221341](https://github.com/Team-xManager/xManager/assets/83493195/d07a8f4b-4cc6-47f5-ab8d-ae1741a0bc1e)
![Screenshot_20240208-221424](https://github.com/Team-xManager/xManager/assets/83493195/34a1ea7a-c46c-4da9-8393-c4a540f1e1d1)

**Comment by julcioo** [comment] 2024-02-08 22:02
bump, also have the same issue.
Device Model: Xiaomi Redmi Note 11 Pro+ 5G
Android Version: Android 13, MIUI 14.0.7
ROM Version: Stock
xManager Version: 5.2

**Comment by shinil171120** [comment] 2024-02-09 00:09
i too have the same issue

**Comment by its-johnny** [comment] 2024-02-09 00:21
bump
same here

**Comment by its-johnny** [comment] 2024-02-09 00:22
bump
same here, happens with new version and older versions. Uninstalling the patched apk or the manager does not solve it.

**Comment by STR33T11** [comment] 2024-02-09 01:31
Same boat...

Lots of typing saved

**Comment by CDRShepard96** [comment] 2024-02-09 03:07
same issue. but the mirror link works yet.

**Comment by Hiker2485Sh** [comment] 2024-02-09 03:50
Same here I can't install the older version either

**Comment by DaN0mic** [comment] 2024-02-09 03:58
> same issue. but the mirror link works yet.

Yes mirror link works, however this will not enable the patches. At least for the newest cloned version. All version downloads are currently broken. I had to install an my old patched apk from a backup I did yesterday.

**Comment by Hiker2485Sh** [comment] 2024-02-09 04:13
> k

can you send the backup apk you have? I tried to download the latest verstion and the apk I had got deleted

**Comment by EncryptedCicada** [comment] 2024-02-09 06:58
Having the same issue here.
Android 13

**Comment by ksw392** [comment] 2024-02-09 07:04
pixel 5, android 14, same here

**Comment by ravindusha** [comment] 2024-02-09 07:14
Same issue here, all downloads are corrupted

**Comment by reloxx13** [comment] 2024-02-09 10:41
You can click on mirror link while the download starts and download ot from the mirror, they work.

**Comment by Rajneesh315** [comment] 2024-02-09 12:11
Sameee

**Comment by CyberAlbSecOP** [comment] 2024-02-09 14:01
Smae here, maybe they have been taken down. I hope not.

**Comment by Mesazane** [comment] 2024-02-09 14:46
Same here. For now I just use the older version with mirror link(since the normal install doesn't work).

**Comment by CyborgRyno603YT** [comment] 2024-02-09 18:25
Same thing here
Motorola G Power, Android 11

**Comment by leSifirus** [comment] 2024-02-09 20:07
same here
Xiaomi Redmi Note 11

**Comment by Rajneesh315** [comment] 2024-02-10 02:54
> same here, by mistake I deleted the previous version and now I don't have any backup haha
> Xiaomi Redmi Note 11

Use the mirror Link for cloned version

**Comment by bladex452** [comment] 2024-02-11 03:45
same problem here. cloned version doesn't work. I don't have a mirror link that shows up. help?

**Comment by DarkCrypt** [comment] 2024-02-13 04:23
Duplicate of numerous closed issues.

**Closed** 2024-02-14 12:49 UTC
