### ISSUE TITLE
Xmanager downloading a much smaller file than normal.

### ISSUE THREAD

**Issue by goliv04053** [Team-xManager/xManager#432] opened 2023-12-15 03:27 UTC
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: Samsung Galaxy M53 5G
- Android Version: Android 13
- ROM Version: stock
- xManager Version: 5.2
```

### 📝 Description

1.Try to download
2. Very small corrupted file
3. Can't install.
...

**Comment by Manurmz** [comment] 2023-12-15 04:14
I have the same problem, I thought I was doing something wrong

**Comment by JamesKpP** [comment] 2023-12-15 05:48
Same here, xManager downloads the latest patched release, with a size of 0.06 MBs, and when trying to install the release I get 'There was a problem parsing the package.'

**Comment by yourfav-raphi** [comment] 2023-12-15 06:07
Got the same issue on my phone

**Comment by urrhen** [comment] 2023-12-15 06:20
Same issue.

**Comment by AnoZu** [comment] 2023-12-15 06:49
same issue on Poco M2 Pro with Android 13

**Comment by RA2112704010015** [comment] 2023-12-15 06:53
Same Issue at Android 13

**Comment by DarkCrypt** [comment] 2023-12-15 07:07
Duplicate of #423, #353, etc.

Download with the mirror link.

**Comment by BunnyGirlMai** [comment] 2023-12-15 15:09
> Duplicate of #423, #353, etc.
> 
> Download with the mirror link.

I think this doesn't work anymore, the mirror links don't open

**Comment by yourfav-raphi** [comment] 2023-12-15 15:10
> > Duplicate of #423, #353, etc.
> > 
> > Download with the mirror link.
> 
> I think this doesn't work anymore, the mirror links don't open

Same here

**Comment by ciganzelezo** [comment] 2023-12-15 17:03
> > > Duplicate of #423, #353, etc.
> > > Download with the mirror link.
> > 
> > 
> > I think this doesn't work anymore, the mirror links don't open
> 
> Same here

it did work for me, opened mediafire with the app, at least for amoled

**Comment by DarkCrypt** [comment] 2023-12-15 18:18
> uninstall the old version

There shouldn't be a need to uninstall the old version. I've never had to do that. If it tells you to do that hit ignore and install over previous version.

> the mirror links don't open

All mirror links open for me. This is the only way I download the patches. The in-app downloader never works correctly for me.
___
You can try:

1. Clear Xmanager cache and retry downloading. This will clear any bullshit downloads.
2. Hit refetch and reboot button within in-app settings. Then retry downloading. This refreshes all data.

**Comment by xC3FFF0E** [comment] 2023-12-16 08:58
All links should be up by now. Closing.

If the persists, visit one of our support teams for further assistance. Thanks!

**Closed by xC3FFF0E** 2023-12-16 08:58 UTC
