### ISSUE TITLE
Issue in lyrics box 

### ISSUE THREAD

**Issue by alamf3320** [Team-xManager/xManager#526] opened 2024-07-27 19:28 UTC
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  iqoo neo 7
- Android Version:  14
- ROM Version:  mediatek
- xManager Version:  latest (can't remember the version but it's latest)
```

### 📝 Description

1. In song lyrics box, there is an error, we can't see the lyrics of any song. It shows lyrics can't be load.
2. Fix this issue 
3. Please 
4.
5.
...

### 📸 Screenshots

![Uploading Screenshot_20240728_005748_com.spotify.music.jpg…]()

**Comment by Schweeeeeeeeeeeeeeee** [comment] 2024-08-04 10:30
Your screenshot didnt even upload

**Comment by WinnerWind** [comment] 2024-08-06 15:27
Duplicate of issue #412.

**Comment by xC3FFF0E** [comment] 2024-09-09 04:07
xManager GitHub repo is for xManager app alone only. For suggestions, updates, etc., please visit one of our support channels:

* **Discord:** https://discord.gg/dnpKn5Wufm  
* **Reddit:** https://www.reddit.com/r/xManagerApp/  
* **Telegram (xManager Updates):** https://t.me/xManagerUpdates  
* **Telegram (Support):** https://t.me/xManagerSupport

**Closed by xC3FFF0E** 2024-09-09 04:07 UTC
